version: 2.1
jobs:
  push:
    docker:
      - image: redocly/cli
    parameters:
      files:
        description: Files to push
        type: string
      organization:
        description: Organization name
        type: string
      project:
        description: Project name
        type: string
      mountPath:
        description: Mount path
        type: string
      currentBranch:
        description: Current branch
        type: string
        default: '<< pipeline.git.branch >>'
      defaultBranch:
        description: Default branch
        type: string
        default: 'main'
      commitMessage:
        description: Commit message
        type: string
      commitTimestamp:
        description: Commit timestamp
        type: string
      repositoryName:
        description: Repository name
        type: string
      namespace:
        description: Repository owner
        type: string
        default: ''
      domain:
        description: Domain name
        type: string
        default: 'https://app.cloud.redocly.com'
    steps:
      - checkout
      - run:
          name: 'Push files and wait for deployment'
          command: |-
            echo "CIRCLE_SHA1=$CIRCLE_SHA1"
            REPO_NAME="<< parameters.repositoryName >>";
            NAMESPACE="<< parameters.namespace >>"
            NAMESPACE="${NAMESPACE:-$(basename $(echo "<< pipeline.trigger_parameters.github_app.repo_url >>" | sed "s/$REPO_NAME//p"))}"

            redocly push << parameters.files >> \
              --organization "<< parameters.organization >>" \
              --project "<< parameters.project >>" \
              --mount-path "<< parameters.mountPath >>" \
              --default-branch "<< parameters.defaultBranch >>" \
              --branch "<< parameters.currentBranch >>" \
              --author "$(git log --format='%an <%ae>' "$CIRCLE_SHA1"^!)" \
              --commit-sha "$CIRCLE_SHA1" \
              --commit-url "<< pipeline.trigger_parameters.github_app.repo_url >>/commit/$CIRCLE_SHA1" \
              --created-at "<< parameters.commitTimestamp >>" \
              --repository "$REPO_NAME" \
              --namespace "$NAMESPACE" \
              --message "<< parameters.commitMessage >>" \
              --domain "<< parameters.domain >>" \
              --wait-for-deployment
workflows:
  push-to-redocly:
    jobs:
      - push:
          files: 'README.md'
          organization: 'default'
          project: 'pushes-testing'
          mountPath: '/remotes/cicd/useful-links'
          domain: 'http://localhost'
          repositoryName: << pipeline.trigger_parameters.github_app.repo_name >>
          commitMessage: << pipeline.trigger_parameters.github_app.commit_message >>
          commitTimestamp: << pipeline.trigger_parameters.github_app.commit_timestamp >>
          defaultBranch: 'main'
          namespace: 'roman-sainchuk'